package jan21.exceptiondemo;

public class ArrayDemo {
    public static void main(String[] args) {
        int[] arr = {10,20,40,540,50};

        System.out.println(arr[0]);
        System.out.println(arr[1]);
        System.out.println(arr[2]);
        System.out.println(arr[3]);
        System.out.println(arr[4]);
        System.out.println(arr[5]); // exception occured here

        System.out.println("End o");

      //   Thread.sleep(1000); // checked exception


    }
}
